### ISSUE TITLE
Sounds are not getting played

### ISSUE THREAD

**Issue by emign** [korlibs/korau#2]
Reproduce with this minimal sample:[https://github.com/emign/korAuNoSoundSample](https://github.com/emign/korAuNoSoundSample)

Sound does not get played. Neither in JS nor JVM targets.
JVM target does open the korge window but does throw this error:

```
WARNING. Slower startup: NOT in main thread! Using AWT! (on mac use -XstartOnFirstThread when possible)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.soywiz.korgw.awt.AwtGameWindow$frame$1 (file:/Users/nicolaiemig/Downloads/untitled1/build/libs/untitled1-all-4.10.1.jar) to method sun.java2d.opengl.OGLUtilities.invokeWithOGLContextCurrent(java.awt.Graphics,java.lang.Runnable)
WARNING: Please consider reporting this to the maintainers of com.soywiz.korgw.awt.AwtGameWindow$frame$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Error trying to get URLs from classloader jdk.internal.loader.ClassLoaders$AppClassLoader@55054057
java.lang.reflect.InaccessibleObjectException: Unable to make field final jdk.internal.loader.URLClassPath jdk.internal.loader.ClassLoaders$AppClassLoader.ucp accessible: module java.base does not "opens jdk.internal.loader" to unnamed module @325fbc0c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:344)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:284)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at com.soywiz.korio.dynamic.DynamicInternal.tryGetField(DynamicInternal.kt:14)
	at com.soywiz.korio.dynamic.DynamicInternal.get(DynamicInternal.kt:64)
	at com.soywiz.korio.dynamic.KDynamic.get(KDynamic.kt:42)
	at com.soywiz.korio.file.std.LocalVfsJvmKt.tryGetURLs(LocalVfsJvm.kt:50)
	at com.soywiz.korio.file.std.ResourcesVfsProviderJvm$invoke$1.init(LocalVfsJvm.kt:81)
	at com.soywiz.korio.file.Vfs$Proxy.initOnce(Vfs.kt:144)
	at com.soywiz.korio.file.Vfs$Proxy.getUnderlyingUnscapedFile(Vfs.kt:135)
	at com.soywiz.korio.file.VfsFile.getUnderlyingUnscapedFile(VfsFile.kt:217)
	at com.soywiz.korio.file.Vfs$Proxy.getUnderlyingUnscapedFile(Vfs.kt:135)
	at com.soywiz.korio.file.VfsFile.getUnderlyingUnscapedFile(VfsFile.kt:217)
	at com.soywiz.korim.format.NativeImageFormatProvider.decode(NativeImageFormatProvider.kt:17)
	at com.soywiz.korim.format.NativeImageFormatProvider.decode(NativeImageFormatProvider.kt:23)
	at com.soywiz.korim.format.KorioExtKt.readBitmap(KorioExt.kt:102)
	at com.soywiz.korim.format.KorioExtKt.readBitmap$default(KorioExt.kt:98)
	at MainKt$main$2.invokeSuspend(main.kt:17)
	at MainKt$main$2.invoke(main.kt)
	at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:459)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:91)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:190)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:112)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:830)
java.util.ServiceConfigurationError: com.soywiz.korau.format.AudioFormat: com.soywiz.korau.format.mp3.MP3Decoder Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
	at com.soywiz.korau.sound.AwtNativeSoundProviderKt.<clinit>(AwtNativeSoundProvider.kt:19)
	at com.soywiz.korau.sound.NativeSoundKt.readNativeSound(NativeSound.kt:116)
	at com.soywiz.korau.sound.NativeSoundKt.readNativeSound$default(NativeSound.kt:116)
	at MainKt$main$2.invokeSuspend(main.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:91)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:190)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:112)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoSuchMethodException: com.soywiz.korau.format.mp3.MP3Decoder.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getConstructor(Class.java:2152)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:661)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:658)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:669)
	... 18 more
Exception in thread "Java2D Queue Flusher" java.util.ServiceConfigurationError: com.soywiz.korau.format.AudioFormat: com.soywiz.korau.format.mp3.MP3Decoder Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:583)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1233)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
	at com.soywiz.korau.sound.AwtNativeSoundProviderKt.<clinit>(AwtNativeSoundProvider.kt:19)
	at com.soywiz.korau.sound.NativeSoundKt.readNativeSound(NativeSound.kt:116)
	at com.soywiz.korau.sound.NativeSoundKt.readNativeSound$default(NativeSound.kt:116)
	at MainKt$main$2.invokeSuspend(main.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at com.soywiz.korgw.GameWindowCoroutineDispatcher.executePending(GameWindow.kt:91)
	at com.soywiz.korgw.GameWindow.frame(GameWindow.kt:190)
	at com.soywiz.korgw.awt.AwtGameWindow$frame$1$paint$2.run(AwtGameWindow.kt:112)
	at java.desktop/sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:231)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.NoSuchMethodException: com.soywiz.korau.format.mp3.MP3Decoder.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getConstructor(Class.java:2152)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:661)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:658)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:669)
	... 18 more
```

**Comment by soywiz** [comment]
I need to put some integration tests to the ServiceLoader to ensure this doesn't happen again

**Comment by emign** [comment]
Thanks. Keep us posted :)
