### ISSUE TITLE
Korge sound broken on Android

### ISSUE THREAD

**Issue by soywiz** [korlibs/korau#3]
Reported here: https://soywiz.slack.com/archives/CH2RW1UH5/p1578859800019800

```
Process: de.tfr.game.hitclack, PID: 26825 java.lang.IllegalStateException: Android context not set! Please call `withAndroidContext()` method in your coroutine body
       at com.soywiz.korio.android.KorioAndroidContextKt.androidContext(KorioAndroidContext.kt:24)
       at com.soywiz.korio.file.std.ResourcesVfsProviderAndroid$invoke$1.init(VfsAndroid.kt:45)
       at com.soywiz.korio.file.Vfs$Proxy.initOnce(Vfs.kt:144)
       at com.soywiz.korio.file.Vfs$Proxy.getUnderlyingUnscapedFile(Vfs.kt:135)
       at com.soywiz.korio.file.VfsFile.getUnderlyingUnscapedFile(VfsFile.kt:217)
       at com.soywiz.korio.file.Vfs$Proxy.getUnderlyingUnscapedFile(Vfs.kt:135)
       at com.soywiz.korio.file.VfsFile.getUnderlyingUnscapedFile(VfsFile.kt:217)
       at com.soywiz.korau.sound.NativeSoundProvider.createSound(NativeSound.kt:41)
       at com.soywiz.korau.sound.NativeSoundKt.readNativeSound(NativeSound.kt:116)
       at com.soywiz.korau.sound.NativeSoundKt.readNativeSound$default(NativeSound.kt:116)
       at de.tfr.game.SoundMachine.newSound(SoundMachine.kt:18)
       at de.tfr.game.SoundMachine.create(SoundMachine.kt:21)
       at de.tfr.game.BoxGame.create(BoxGame.kt:30)
       at de.tfr.game.HitKlack.create(HitKlack.kt:34)
       at MainKt$main$2.invokeSuspend(main.kt:13)
       at MainKt$main$2.invoke(Unknown Source:10)
       at com.soywiz.korge.Korge$invoke$2$3.invokeSuspend(Korge.kt:464)
       at com.soywiz.korge.Korge$invoke$2$3.invoke(Unknown Source:10)
       at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
       at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
       at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
       at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
       at com.soywiz.korio.async.AsyncExtKt.launchImmediately(AsyncExt.kt:9)
       at com.soywiz.korge.Korge$invoke$2.invokeSuspend(Korge.kt:463)
       at com.soywiz.korge.Korge$invoke$2.invoke(Unknown Source:10)
       at com.soywiz.korge.Korge$KoruiWithLogger$2.invokeSuspend(Korge.kt:408)
       at com.soywiz.korge.Korge$KoruiWithLogger$2.invoke(Unknown Source:10)
       at com.soywiz.korgw.AndroidGameWindow.loop(DefaultGameWindowAndroid.kt:74)
       at com.soywiz.korge.Korge.KoruiWithLogger(Korge.kt:407)
       at com.soywiz.korge.Korge.invoke-nom0QHw(Korge.kt:432)
       at com.soywiz.korge.Korge.invoke-nom0QHw$default(Korge.kt:430)
       at MainKt.main(main.kt:10)
       at de.tfr.game.hitclack.MainActivity.activityMain(MainActivity.kt:13)
       at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invokeSuspend(KorgwActivity.kt:169)
       at com.soywiz.korgw.KorgwActivity$onCreate$2$1.invoke(Unknown Source:10)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
       at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
       at com.soywiz.korgw.KorgwActivity$onCreate$2.invokeSuspend(KorgwActivity.kt:168)
       at com.soywiz.korgw.KorgwActivity$onCreate$2.invoke(Unknown Source:10)
       at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invokeSuspend(KorioAndroid.kt:8)
       at com.soywiz.korio.KorioAndroidKt$Korio$1$1.invoke(Unknown Source:10)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
       at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
       at com.soywiz.korio.android.KorioAndroidContextKt.withAndroidContext(KorioAndroidContext.kt:19)
       at com.soywiz.korio.KorioAndroidKt$Korio$1.invokeSuspend(KorioAndroid.kt:8)
       at com.soywiz.korio.KorioAndroidKt$Korio$1.invoke(Unknown Source:10)
       at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invokeSuspend(AsyncExtAndroid.kt:7)
       at com.soywiz.korio.async.AsyncExtAndroidKt$asyncEntryPoint$1.invoke(Unknown Source:10)
       at com.soywiz.korio.async.AsyncExtKt$_launch$1.invokeSuspend(AsyncExt.kt:34)
       at com.soywiz.korio.async.AsyncExtKt$_launch$1.invoke(Unknown Source:10)
       at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
       at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
       at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
       at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
       at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
       at com.soywiz.korio.async.AsyncExtKt._launch(AsyncExt.kt:32)
       at com.soywiz.korio.async.AsyncExtKt.launch(AsyncExt.kt:8)
       at com.soywiz.korio.async.AsyncExtAndroidKt.asyncEntryPoint(AsyncExtAndroid.kt:6)
       at com.soywiz.korio.KorioAndroidKt.Korio(KorioAndroid.kt:8)
       at com.soywiz.korgw.KorgwActivity.onCreate(KorgwActivity.kt:166)
       at android.app.Activity.performCreate(Activity.java:7159)
       at android.app.Activity.performCreate(Activity.java:7150)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3001)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3156)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1864)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:205)
       at android.app.ActivityThread.main(ActivityThread.java:6991)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by soywiz** [comment]
Investigate if this is the culprit: https://github.com/korlibs/korge/blob/0da41887d21ee2f16bc2c12eed5656d1b24f5c26/korge/src/commonMain/kotlin/com/soywiz/korge/Korge.kt#L463
